const data = {
  user: {
    id: 1,
    firstname: 'Kossy',
    secondname: 'Ugochukwu',
    othername: 'Ugochukwu',
    email: 'kossyugochukwu@gmail.com',
    phoneNumber: '08170336933',
    username: 'kossy360',
    registered: '11/11/11',
    idAdmin: false,
  },

  meetups: [{
    id: 1,
    title: 'Building of the second Niger Bridge',
    location: 'Abuja',
    date: '11/11/11',
    time: '3:00',
    rsvp: { yes: 10, maybe: 10, no: 10 },
    questions: 50,
    tags: ['infrastructure', 'transport', 'economy', 'technology', 'growth'],
    images: [],

  }, {
    id: 2,
    title: 'Building of the second Niger Bridge',
    location: 'Abuja',
    date: '11/11/11',
    time: '3:00',
    rsvp: { yes: 10, maybe: 10, no: 10 },
    questions: 50,
    tags: ['infrastructure', 'transport', 'economy', 'technology', 'growth'],
    images: [],

  }, {
    id: 3,
    title: 'Building of the second Niger Bridge',
    location: 'Abuja',
    date: '11/11/11',
    time: '3:00',
    rsvp: { yes: 10, maybe: 10, no: 10 },
    questions: 50,
    tags: ['infrastructure', 'transport', 'economy', 'technology', 'growth'],
    images: [],

  }, {
    id: 4,
    title: 'Building of the second Niger Bridge',
    location: 'Abuja',
    date: '11/11/11',
    time: '3:00',
    rsvp: { yes: 10, maybe: 10, no: 10 },
    questions: 50,
    tags: ['infrastructure', 'transport', 'economy', 'technology', 'growth'],
    images: [],

  }],

  questions: [{
    id: 1,
    createdOn: '11/11/11',
    createdBy: 1,
    username: 'kossy360',
    meetup: 1,
    body: 'is this gesture going to continue?',
    votes: 25,
  }, {
    id: 1,
    createdOn: '11/11/11',
    createdBy: 1,
    username: 'kossy360',
    meetup: 1,
    body: 'is this gesture going to continue?',
    votes: 25,
  }, {
    id: 1,
    createdOn: '11/11/11',
    createdBy: 1,
    username: 'kossy360',
    meetup: 1,
    body: 'is this gesture going to continue?',
    votes: 25,
  }, {
    id: 1,
    createdOn: '11/11/11',
    createdBy: 1,
    username: 'kossy360',
    meetup: 1,
    body: 'is this gesture going to continue?',
    votes: 25,
  }],

  comments: [{
    id: 1,
    createdOn: '11/11/11',
    createdBy: 1,
    username: 'kossy360',
    question: 1,
    body: 'this is a very onpoint move by the government',
  }, {
    id: 1,
    createdOn: '11/11/11',
    createdBy: 1,
    username: 'kossy360',
    question: 1,
    body: 'this is a very onpoint move by the government',
  }, {
    id: 1,
    createdOn: '11/11/11',
    createdBy: 1,
    username: 'kossy360',
    question: 1,
    body: 'this is a very onpoint move by the government',
  }, {
    id: 1,
    createdOn: '11/11/11',
    createdBy: 1,
    username: 'kossy360',
    question: 1,
    body: 'this is a very onpoint move by the government',
  }, {
    id: 1,
    createdOn: '11/11/11',
    createdBy: 1,
    username: 'kossy360',
    question: 1,
    body: 'this is a very onpoint move by the government',
  }, {
    id: 1,
    createdOn: '11/11/11',
    createdBy: 1,
    username: 'kossy360',
    question: 1,
    body: 'this is a very onpoint move by the government',
  }, {
    id: 1,
    createdOn: '11/11/11',
    createdBy: 1,
    username: 'kossy360',
    question: 1,
    body: 'this is a very onpoint move by the government',
  }, {
    id: 1,
    createdOn: '11/11/11',
    createdBy: 1,
    username: 'kossy360',
    question: 1,
    body: 'this is a very onpoint move by the government',
  }, {
    id: 1,
    createdOn: '11/11/11',
    createdBy: 1,
    username: 'kossy360',
    question: 1,
    body: 'this is a very onpoint move by the government',
  }],

  notifications: [{
    meetId: 1,
    title: 'Building of the second Niger bridge',
    count: 5,
  },
  {
    meetId: 1,
    title: 'Building of the second Niger bridge',
    count: 5,
  }, {
    meetId: 1,
    title: 'Building of the second Niger bridge',
    count: 5,
  }, {
    meetId: 1,
    title: 'Building of the second Niger bridge',
    count: 5,
  },
  ],
};

export default data;
