const data = {
  user: {
    id: 1,
    firstname: 'Kossy',
    lastname: 'Ugochukwu',
    othername: 'Ugochukwu',
    email: 'kossyugochukwu@gmail.com',
    phoneNumber: '08170336933',
    username: 'kossy360',
    registered: '11/11/11',
    idAdmin: false,
  },

  meetups: [{
    id: 1,
    title: 'Building of the second Niger Bridge',
    location: 'Abuja',
    date: '11/11/11',
    time: '3:00',
    tags: ['infrastructure', 'transport', 'economy', 'technology', 'growth'],
    rsvp: 'yes',
    questions: 50,
    images: ['../assets/meeting1.jpg', '../assets/meeting1.jpg', '../assets/meeting1.jpg'],
  }, {
    id: 1,
    title: 'Building of the second Niger Bridge',
    location: 'Abuja',
    date: '11/11/11',
    time: '3:00',
    tags: ['infrastructure', 'transport', 'economy', 'technology', 'growth'],
    rsvp: 'yes',
    questions: 50,
    images: [],
  }, {
    id: 1,
    title: 'Building of the second Niger Bridge',
    location: 'Abuja',
    date: '11/11/11',
    time: '3:00',
    tags: ['infrastructure', 'transport', 'economy', 'technology', 'growth'],
    rsvp: 'yes',
    questions: 50,
    images: [],
  }, {
    id: 1,
    title: 'Building of the second Niger Bridge',
    location: 'Abuja',
    date: '11/11/11',
    time: '3:00',
    tags: ['infrastructure', 'transport', 'economy', 'technology', 'growth'],
    rsvp: 'yes',
    questions: 50,
    images: [],
  }],

  questions: [{
    id: 1,
    createdOn: '11/11/11',
    createdBy: 1,
    username: 'kossy360',
    meetup: 1,
    body: 'is this gesture going to continue?',
    votes: 25,
  }, {
    id: 2,
    createdOn: '11/11/11',
    createdBy: 1,
    username: 'kossy360',
    meetup: 1,
    body: 'is this gesture going to continue?',
    votes: 25,
  }, {
    id: 3,
    createdOn: '11/11/11',
    createdBy: 1,
    username: 'kossy360',
    meetup: 1,
    body: 'is this gesture going to continue?',
    votes: 25,
  }, {
    id: 4,
    createdOn: '11/11/11',
    createdBy: 1,
    username: 'kossy360',
    meetup: 1,
    body: 'is this gesture going to continue?',
    votes: 25,
  }],

  comments: [{
    id: 1,
    createdOn: '11/11/11',
    createdBy: 1,
    username: 'kossy360',
    question: 1,
    body: 'this is a very onpoint move by the government',
  }, {
    id: 1,
    createdOn: '11/11/11',
    createdBy: 1,
    username: 'kossy360',
    question: 1,
    body: 'this is a very onpoint move by the government',
  }, {
    id: 1,
    createdOn: '11/11/11',
    createdBy: 1,
    username: 'kossy360',
    question: 1,
    body: 'this is a very onpoint move by the government',
  }, {
    id: 1,
    createdOn: '11/11/11',
    createdBy: 1,
    username: 'kossy360',
    question: 1,
    body: 'this is a very onpoint move by the government',
  }, {
    id: 1,
    createdOn: '11/11/11',
    createdBy: 1,
    username: 'kossy360',
    question: 1,
    body: 'this is a very onpoint move by the government',
  }],

  rsvps: [{
    id: 1,
    meetup: 1,
    user: 1,
    title: 'Building of the second Niger bridge',
    response: 'yes',
  }, {
    id: 1,
    meetup: 1,
    user: 1,
    title: 'Building of the second Niger bridge',
    response: 'yes',
  }, {
    id: 1,
    meetup: 1,
    user: 1,
    title: 'Building of the second Niger bridge',
    response: 'yes',
  }, {
    id: 1,
    meetup: 1,
    user: 1,
    title: 'Building of the second Niger bridge',
    response: 'yes',
  }, {
    id: 1,
    meetup: 1,
    user: 1,
    title: 'Building of the second Niger bridge',
    response: 'yes',
  }],

  notifications: [{
    meetId: 1,
    title: 'Building of the second Niger bridge',
    count: 5,
  },
  {
    meetId: 1,
    title: 'Building of the second Niger bridge',
    count: 5,
  }, {
    meetId: 1,
    title: 'Building of the second Niger bridge',
    count: 5,
  }, {
    meetId: 1,
    title: 'Building of the second Niger bridge',
    count: 5,
  },
  ],
};

export default data;
